// The shared synthetic teaching trace for SLOP6246.
//
// THIS IS NOT MEASURED DATA. The series below is generated by the seeded
// function in this file. It is not reanalysis, not a historical record, and it
// does not describe any real electricity system. Anything derived from it is
// `synthetic` provenance under CLAUDE.md §6 and must be labelled as such
// wherever it reaches a reader.
//
// It exists so the whole course argues about one fortnight. Every figure, week
// activity and assessment example reads from here rather than generating its
// own series, so no two pages can quietly disagree about the reference event.
//
// Units: every value in `wind`, `solar` and `total` is a PERCENTAGE of the
// system's combined installed wind and solar capacity. They are not megawatts,
// and this module deliberately carries no capacity figure — the course's
// threshold is defined as a proportion, so no absolute denominator is needed
// and inventing one would be an unsupported claim.

/** Linear congruential generator. Seeded so the trace is identical on every
 *  build, which is what lets separate pages cite the same numbers. */
function lcg(seed: number): () => number {
  let state = seed;
  return () => {
    state = (state * 1664525 + 1013904223) % 4294967296;
    return state / 4294967296;
  };
}

const SEED = 20260914;

/** Fourteen days at hourly resolution. */
export const TRACE_HOURS = 336;

/** Where the reference event begins, as an hour index into the trace. Hour 187
 *  falls inside day 8, which is why the course calls it the day 8–10 event. */
export const EVENT_START_HOUR = 187;

/** How long the reference event runs. The generator writes it as one
 *  contiguous block, so this is both the event's span and its count of hours
 *  below the threshold — there is no interior recovery. */
export const EVENT_LENGTH_HOURS = 61;

// ---------------------------------------------------------------------------
// The course's operative definition (CLAUDE.md §4, /the-event/). These are
// `defined` provenance: boundaries the course chose, not measurements.
// ---------------------------------------------------------------------------

/** Combined wind + solar output, as a percentage of combined installed
 *  capacity, below which an hour counts as below threshold. */
export const THRESHOLD_PCT = 12;

/** Minimum event span, in hours, for a period to qualify. */
export const MIN_SPAN_HOURS = 48;

/** A recovery above the threshold ends an event only if it runs longer than
 *  this many hours. */
export const RECOVERY_ALLOWANCE_HOURS = 3;

export interface Trace {
  /** Wind output, % of combined installed capacity, one entry per hour. */
  readonly wind: readonly number[];
  /** Solar output, % of combined installed capacity, one entry per hour. */
  readonly solar: readonly number[];
  /** Wind + solar, % of combined installed capacity, one entry per hour. */
  readonly total: readonly number[];
}

function build(): Trace {
  const random = lcg(SEED);
  const wind: number[] = [];
  const solar: number[] = [];
  const total: number[] = [];

  for (let h = 0; h < TRACE_HOURS; h++) {
    const day = h / 24;
    const hourOfDay = h % 24;
    const inEvent = h >= EVENT_START_HOUR && h < EVENT_START_HOUR + EVENT_LENGTH_HOURS;

    // Output decays into the event over ~22 h and recovers over ~26 h, so the
    // trough has shoulders rather than square edges.
    const eventEnd = EVENT_START_HOUR + EVENT_LENGTH_HOURS;
    const ramp = inEvent
      ? 1
      : h > EVENT_START_HOUR - 22 && h < EVENT_START_HOUR
        ? (EVENT_START_HOUR - h) / 22
        : h >= eventEnd && h < eventEnd + 26
          ? (h - eventEnd) / 26
          : 1;

    // Wind: a slow synoptic swing plus a faster one plus noise. Inside the
    // event it is pinned low instead, which is what makes the event an event.
    let w = 28 + 19 * Math.sin(day * 1.7 + 0.6) + 11 * Math.sin(day * 4.3) + 6 * (random() - 0.5);
    w = Math.max(1.5, w);
    if (inEvent) w = 2.0 + 2.0 * random() + 1.4 * Math.sin(h * 0.4);
    else w *= Math.min(1, 0.22 + 0.78 * ramp);

    // Solar: a daylight half-sine, so it is zero overnight in every hour of
    // the trace, event or not. Inside the event the daytime peak is overcast.
    const daylight = Math.max(0, Math.sin(((hourOfDay - 6.5) / 11.5) * Math.PI));
    let s = daylight * (18 + 5 * Math.sin(day * 2.1) + 4 * (random() - 0.5));
    if (inEvent) s = daylight * (1.5 + 0.9 * random());
    s = Math.max(0, s);

    wind.push(w);
    solar.push(s);
    total.push(w + s);
  }

  return { wind, solar, total };
}

/** The trace. Built once per module evaluation, so every importer sees the
 *  same numbers within a build. */
export const trace: Trace = build();

/** Hours in the trace whose combined output sits below a threshold. */
export function hoursBelow(thresholdPct: number = THRESHOLD_PCT): number {
  return trace.total.filter((value) => value < thresholdPct).length;
}

/** Lowest combined output across a half-open hour range. */
export function minimumIn(startHour: number, endHour: number): number {
  return Math.min(...trace.total.slice(startHour, endHour));
}

/** Mean combined output across a half-open hour range. */
export function meanIn(startHour: number, endHour: number): number {
  const window = trace.total.slice(startHour, endHour);
  return window.reduce((sum, value) => sum + value, 0) / window.length;
}

/** The reference event, as the course cites it. Every field is `synthetic`
 *  provenance except the two threshold/duration boundaries it is judged
 *  against, which are `defined`. */
export const referenceEvent = {
  startHour: EVENT_START_HOUR,
  lengthHours: EVENT_LENGTH_HOURS,
  /** Day 8 to day 10, from the start hour and length. */
  startDay: Math.floor(EVENT_START_HOUR / 24) + 1,
  endDay: Math.floor((EVENT_START_HOUR + EVENT_LENGTH_HOURS - 1) / 24) + 1,
  /** Lowest combined output reached inside the event, % of capacity. */
  minimumPct: minimumIn(EVENT_START_HOUR, EVENT_START_HOUR + EVENT_LENGTH_HOURS),
} as const;
